[build]
  publish = "."
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"

[[redirects]]
  from = "/articles/*"
  to = "/articles/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/privacy-policy.html"
  to = "/privacy-policy.html"
  status = 200
  force = false

[[redirects]]
  from = "/v/*"
  to = "/v/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
